/*
 * Orders.
 *
 * Placement is the one operation in this codebase where getting it slightly
 * wrong costs money, so three things are deliberate:
 *
 * 1. **Totals are recomputed from the database.** Nothing the client sends about
 *    price is read. The browser's idea of the total is a display; the order's
 *    total is derived from the products and the coupon as they are right now.
 *
 * 2. **Line items are snapshotted.** Title, slug, type and unit price are copied
 *    onto the order. Editing or deleting a product later must not rewrite what
 *    someone was charged.
 *
 * 3. **It is idempotent.** A double-clicked button, a retried request after a
 *    timeout, or a flaky connection must not produce two orders and two
 *    payments. The cart is converted inside the transaction, so a second attempt
 *    finds it already converted and returns the same order.
 */

const crypto = require('node:crypto');
const prisma = require('../../lib/prisma');
const env = require('../../config/env');
const ApiError = require('../../lib/ApiError');
const settings = require('../../lib/settings');
const cartService = require('../cart/cart.service');
const razorpay = require('../../lib/razorpay');
const { toRupees } = require('../../lib/money');
const { writeAudit } = require('../../lib/audit');
const logger = require('../../lib/logger');

/*
 * Order numbers are ARV-2026-00001 — human-readable, sortable, and quotable over
 * the phone, which is what they are actually for.
 *
 * Generated by counting the year's orders rather than a database sequence, then
 * retried on collision. Two orders placed in the same millisecond can race; the
 * unique constraint catches it and the retry picks the next number. A sequence
 * would avoid the retry but would also leak the count and skip numbers on every
 * rolled-back transaction.
 */
const nextOrderNumber = async (tx, prefix) => {
  const year = new Date().getFullYear();
  const count = await tx.order.count({
    where: { orderNumber: { startsWith: `${prefix}-${year}-` } },
  });
  return `${prefix}-${year}-${String(count + 1).padStart(5, '0')}`;
};

const ORDER_INCLUDE = {
  items: true,
  patients: true,
  address: true,
  center: true,
  coupon: true,
  payments: { orderBy: { createdAt: 'desc' } },
  statusEvents: { orderBy: { createdAt: 'asc' } },
};

const serialize = (order) => ({
  id: order.id,
  orderNumber: order.orderNumber,
  status: order.status,
  paymentStatus: order.paymentStatus,

  contact: {
    name: order.contactName,
    phone: order.contactPhone,
    email: order.contactEmail,
  },

  collection: {
    type: order.collectionType,
    center: order.center
      ? { id: order.center.id, name: order.center.name, address: order.center.address }
      : null,
    // Requested, not confirmed — capacity-based availability is deferred, so the
    // lab confirms these by phone. The wording matters here.
    requestedDate: order.slotDate,
    requestedWindow:
      order.slotStartTime && order.slotEndTime
        ? { start: order.slotStartTime, end: order.slotEndTime }
        : null,
  },

  address: order.address
    ? {
        line1: order.address.line1,
        line2: order.address.line2,
        landmark: order.address.landmark,
        city: order.address.city,
        state: order.address.state,
        pincode: order.address.pincode,
        phone: order.address.phone,
      }
    : null,

  patients: order.patients.map((p) => ({
    id: p.id,
    name: p.name,
    age: p.age,
    gender: p.gender,
    phone: p.phone,
    relation: p.relation,
  })),

  items: order.items.map((i) => ({
    id: i.id,
    productId: i.productId,
    title: i.productTitle,
    slug: i.productSlug,
    type: i.productType,
    quantity: i.quantity,
    unitPrice: i.unitPrice,
    unitPriceRupees: toRupees(i.unitPrice),
    lineTotal: i.lineTotal,
    lineTotalRupees: toRupees(i.lineTotal),
  })),

  totals: {
    subtotal: order.subtotal,
    discount: order.discountTotal,
    collectionFee: order.collectionFee,
    tax: order.taxTotal,
    total: order.total,
    subtotalRupees: toRupees(order.subtotal),
    discountRupees: toRupees(order.discountTotal),
    collectionFeeRupees: toRupees(order.collectionFee),
    taxRupees: toRupees(order.taxTotal),
    totalRupees: toRupees(order.total),
  },

  couponCode: order.couponCode,
  notes: order.notes,
  placedAt: order.placedAt,
  createdAt: order.createdAt,
});

/*
 * The requested collection date, validated against the booking rules.
 *
 * Not availability — there is none. This only rejects dates that are
 * nonsensical: in the past, inside the notice period, or further ahead than the
 * lab plans for.
 */
const validateRequestedSlot = async ({ date, windowId }) => {
  const { windows, minNoticeHours, maxDaysAhead } = await settings.collection();

  const window = windows.find((w) => w.id === windowId);
  if (!window) {
    throw ApiError.unprocessable('Validation failed.', {
      collectionWindow: 'Choose a collection time.',
    });
  }

  const requested = new Date(`${date}T${window.start}:00`);
  if (Number.isNaN(requested.getTime())) {
    throw ApiError.unprocessable('Validation failed.', {
      collectionDate: 'That date is not valid.',
    });
  }

  const earliest = new Date(Date.now() + minNoticeHours * 60 * 60 * 1000);
  if (requested < earliest) {
    throw ApiError.unprocessable('Validation failed.', {
      collectionDate: `Please choose a time at least ${minNoticeHours} hours from now.`,
    });
  }

  const latest = new Date(Date.now() + maxDaysAhead * 24 * 60 * 60 * 1000);
  if (requested > latest) {
    throw ApiError.unprocessable('Validation failed.', {
      collectionDate: `We can only take bookings up to ${maxDaysAhead} days ahead.`,
    });
  }

  return { date: new Date(`${date}T00:00:00.000Z`), start: window.start, end: window.end };
};

/**
 * Place an order from a cart.
 *
 * Returns the order plus the Razorpay handoff the browser needs.
 */
const place = async (input, req) => {
  const cart = await cartService.findOrThrow(input.cartToken);

  if (cart.items.length === 0) {
    throw ApiError.conflict('Your cart is empty.');
  }

  const unavailable = cart.items.filter((i) => i.product.status !== 'PUBLISHED');
  if (unavailable.length) {
    throw ApiError.conflict(
      `${unavailable.map((i) => i.product.title).join(', ')} is no longer available. Please remove it and try again.`,
    );
  }

  const totals = await cartService.computeTotals(cart);
  const { minOrderValuePaise, orderNumberPrefix } = await settings.commerce();

  if (minOrderValuePaise > 0 && totals.total < minOrderValuePaise) {
    throw ApiError.conflict(`The minimum order value is ₹${toRupees(minOrderValuePaise)}.`);
  }

  const slot = await validateRequestedSlot({
    date: input.collectionDate,
    windowId: input.collectionWindow,
  });

  if (input.collectionType === 'WALK_IN' && !input.centerId) {
    throw ApiError.unprocessable('Validation failed.', {
      centerId: 'Choose which centre you will visit.',
    });
  }

  /*
   * Everything from here is one transaction. If the cart cannot be marked
   * converted — because a parallel request got there first — the whole order is
   * rolled back rather than created twice.
   */
  const order = await prisma.$transaction(async (tx) => {
    const fresh = await tx.cart.findUnique({
      where: { id: cart.id },
      select: { status: true, order: { select: { id: true } } },
    });

    if (fresh?.status === 'CONVERTED') {
      // The idempotent path: a retry of a request that already succeeded.
      if (fresh.order?.id) {
        return tx.order.findUnique({ where: { id: fresh.order.id }, include: ORDER_INCLUDE });
      }
      throw ApiError.conflict('This cart has already been turned into an order.');
    }

    const orderNumber = await nextOrderNumber(tx, orderNumberPrefix);

    const created = await tx.order.create({
      data: {
        orderNumber,
        status: 'PENDING_PAYMENT',
        paymentStatus: 'UNPAID',
        cartId: cart.id,

        contactName: input.contact.name,
        contactPhone: input.contact.phone,
        contactEmail: input.contact.email ?? null,

        collectionType: input.collectionType,
        centerId: input.collectionType === 'WALK_IN' ? input.centerId : null,
        slotDate: slot.date,
        slotStartTime: slot.start,
        slotEndTime: slot.end,

        subtotal: totals.subtotal,
        discountTotal: totals.discountTotal,
        collectionFee: totals.collectionFee,
        taxTotal: totals.taxTotal,
        total: totals.total,
        couponId: totals.appliedCoupon?.id ?? null,
        couponCode: totals.appliedCoupon?.code ?? null,

        notes: input.notes ?? null,

        items: {
          create: totals.lines.map(({ item, unitPrice, lineTotal }) => ({
            productId: item.productId,
            // Snapshotted on purpose — see the note at the top of this file.
            productTitle: item.product.title,
            productSlug: item.product.slug,
            productType: item.product.type,
            unitPrice,
            quantity: item.quantity,
            lineTotal,
          })),
        },

        patients: {
          create: input.patients.map((p) => ({
            name: p.name,
            age: p.age ?? null,
            gender: p.gender ?? 'UNDISCLOSED',
            phone: p.phone ?? null,
            relation: p.relation ?? null,
          })),
        },

        ...(input.collectionType === 'HOME'
          ? {
              address: {
                create: {
                  line1: input.address.line1,
                  line2: input.address.line2 ?? null,
                  landmark: input.address.landmark ?? null,
                  city: input.address.city,
                  state: input.address.state,
                  pincode: input.address.pincode,
                  phone: input.address.phone ?? input.contact.phone,
                },
              },
            }
          : {}),

        statusEvents: {
          create: { toStatus: 'PENDING_PAYMENT', note: 'Order placed' },
        },
      },
      include: ORDER_INCLUDE,
    });

    await tx.cart.update({ where: { id: cart.id }, data: { status: 'CONVERTED' } });

    if (totals.appliedCoupon) {
      await tx.coupon.update({
        where: { id: totals.appliedCoupon.id },
        data: { usageCount: { increment: 1 } },
      });
    }

    return created;
  });

  /*
   * The Razorpay order is created *after* the transaction commits.
   *
   * Doing it inside would hold a database transaction open across a third-party
   * network call, and a slow Razorpay would mean held locks. The cost is that a
   * failure here leaves an order in PENDING_PAYMENT with no payment attached —
   * which is recoverable and visible, unlike the alternative.
   */
  let checkout = null;

  if (razorpay.isConfigured) {
    try {
      const rzpOrder = await razorpay.createOrder({
        amount: order.total,
        receipt: order.orderNumber,
        notes: { orderNumber: order.orderNumber, contact: order.contactPhone },
      });

      await prisma.payment.create({
        data: {
          orderId: order.id,
          provider: 'razorpay',
          state: 'CREATED',
          razorpayOrderId: rzpOrder.id,
          amount: order.total,
          currency: 'INR',
        },
      });

      checkout = {
        provider: 'razorpay',
        keyId: razorpay.keyId,
        razorpayOrderId: rzpOrder.id,
        amount: order.total,
        currency: 'INR',
        name: 'Arova Labs',
        description: `Order ${order.orderNumber}`,
        prefill: {
          name: order.contactName,
          contact: order.contactPhone,
          email: order.contactEmail ?? undefined,
        },
      };
    } catch (err) {
      logger.error({ err, orderNumber: order.orderNumber }, 'could not start payment');
      // The order exists and is findable; the client is told payment could not
      // start rather than being left believing the booking failed entirely.
    }
  }

  await writeAudit({
    req,
    action: 'order.placed',
    entityType: 'Order',
    entityId: order.id,
    after: { orderNumber: order.orderNumber, total: order.total, items: order.items.length },
  });

  return {
    order: serialize(order),
    accessToken: await ensureAccessToken(order.id),
    checkout,
  };
};

/*
 * A per-order token, so a customer can open their confirmation from a link
 * without an account.
 *
 * Derived from the order id and a server secret rather than stored: nothing to
 * migrate, nothing to leak from the table, and it cannot be guessed without the
 * secret. It also means a lost link can always be regenerated.
 */
const ensureAccessToken = async (orderId) =>
  crypto
    .createHmac('sha256', env.JWT_ACCESS_SECRET)
    .update(`order:${orderId}`)
    .digest('base64url')
    .slice(0, 32);

const verifyAccessToken = async (orderId, token) => {
  const expected = await ensureAccessToken(orderId);
  const a = Buffer.from(String(token ?? ''));
  const b = Buffer.from(expected);
  // Constant-time: a plain === would leak how much of the token matched.
  return a.length === b.length && crypto.timingSafeEqual(a, b);
};

/** Public lookup: order number plus its token. */
const getByNumber = async (orderNumber, token) => {
  const order = await prisma.order.findUnique({
    where: { orderNumber },
    include: ORDER_INCLUDE,
  });
  if (!order) throw ApiError.notFound('We could not find that order.');

  if (!(await verifyAccessToken(order.id, token))) {
    // Deliberately the same error as "not found": confirming an order number
    // exists would let someone enumerate them.
    throw ApiError.notFound('We could not find that order.');
  }

  return serialize(order);
};

module.exports = {
  place,
  getByNumber,
  serialize,
  ensureAccessToken,
  verifyAccessToken,
  validateRequestedSlot,
  ORDER_INCLUDE,
};
